### ISSUE TITLE
Message number does not work

### ISSUE THREAD

**Issue by simonfrey** [VaguelySerious/gram-node-frontend#5] opened 2019-02-15 10:29 UTC
The number in the red message indicator is always 1 and does not go away.

**Comment by Edeltraudt** [comment] 2019-02-15 10:53
Class `-hidden` can be added to the notification to hide the container.

**Comment by VaguelySerious** [comment] 2019-02-23 13:52
Addressed in [ff8e782](https://github.com/VaguelySerious/gram-node-frontend/commit/ff8e78240f79831d46995ddb11eaced1fffc6dcb).
The indicator will be hidden until the detection of unread messages is implemented, and will then automatically start working as intended.
This should not require users to modify any classes themselves.

**Closed as completed by VaguelySerious** 2019-02-23 13:52 UTC
Labels: bug
